### ISSUE TITLE
Is this project dead or alive?

### ISSUE THREAD

**Issue by s17227213417** [stepelu/lua-sci#12]
SciLua is an important project. But last commit dates back to Q1 2021.

Is this project still active or will be maintained in future?

**Comment by stepelu** [comment]
> SciLua is an important project.
I very much agree!

I do not currently have plans to add new features, but I will be fixing bugs if reported and review PR if submitted.

As LuaJIT is very keen on remaining backward-compatible, scilua still works as expected, for what I know.

The only issue is that the OpenBLAS and LuaJIT versions shipped with ulua (in case you are using that) are quite dated at this point.

Please feel free to ask further questions.
