### ISSUE TITLE
OpenBLAS required?

### ISSUE THREAD

**Issue by ghost** [stepelu/lua-sci#2]
In `sci.alg` you specifically load `libopenblas`. Is this actually a requirement, i.e. does `sci.alg` use any OpenBLAS specific functions, or would any BLAS compatible implementation suffice? I have the Netlib BLAS3 implementation installed (Ubuntu 14.04 package `libblas3_1.2.20110419-7`) and that seems to work as well.

I changed `./sci/alg.lua` to `ffi.load('libblas.so.3')` - i.e. explicit load the library with SOVERSION suffix, because that appears to be safer, as it assures ABI compatibility (and I don't need to install the development package, which would contain `libblas.so`). Alternatively one could use `ffi.load('blas')`, which would load `libblas.so`, which might point to any BLAS version.

**Comment by stepelu** [comment]
Right now OpenBLAS is not required strictly speaking.

However, I will soon start using some LAPACK functions which are included in OpenBLAS but are not part BLAS. 
For this (and for performance) reasons I would advise to install and use OpenBLAS.

This happens automatically if you're using the ULua distribution.

**Comment by ghost** [comment]
Would a LAPACK library, present in `/usr/lib/liblapack.so.3`, be sufficient for that purpose?

**Comment by stepelu** [comment]
Yes it would.

I will make it easier to customise BLAS and LAPACK libraries in the next
release.

Out of curiosity, what is your use case?

**Comment by ghost** [comment]
I have a 2 year old simulation software that uses a custom Eigen wrapper, which is implemented pretty inefficiently, which I would like to bring up to speed. Therefore I am looking at alternatives to compare them with each other in terms of performance.

Please feel free to close this issue, as my question was answered sufficiently.
