### ISSUE TITLE
Release on LuaRocks

### ISSUE THREAD

**Issue by jirutka** [stepelu/lua-sci#3]
Could you please release this module on https://luarocks.org (de facto standard repository for Lua modules)?

**Comment by tastyminerals** [comment]
+1, this integration with **ulua** is just "meh" imho. 
Why? In order to run **scilua** code I need to run `scilua` binary from `~/ulua/bin` because it does not work otherwise. So, you need to keep both packages, in my case, **torch** and **ulua** when you could get everything under **luarocks** umbrella and thus wonderful **itorch**.

**Comment by FuriouslyCurious** [comment]
Seconded - it will be great to see sci-lua work side-by-side with Torch.

**Comment by stepelu** [comment]
@tastyminerals: you don't need to invoke `/ulua/bin/scilua` to use the scilua library unless you want to the sci syntax extensions (i.e. everything `[]`), in which case you would need to run the `scilua` script even with luarocks.

That aside, I would be happy to submit scilua to luarocks as well in case someone provides a working rockspec for the package. Keep in mind there is the dependency on OpenBLAS.

**Comment by RoyiAvital** [comment]
What's the best way to have SciLua + OpenBLAS working on ZeroBrane IDE?

I'm a newbie and want to try working on LuaJit + SciLua.

**Comment by aktau** [comment]
This seems to have already been done: https://luarocks.org/modules/stepelu/sci

**Comment by stepelu** [comment]
Yes, this should be fixed, please re-open if the provided rock doesn't work.

**Comment by rickhg12hs** [comment]
Could the `luarocks` `sci` be updated for `lua` v. 5.4.4?

**Comment by stepelu** [comment]
The sci library requires LuaJIT.

**Comment by rickhg12hs** [comment]
@stepelu Understood.
