### ISSUE TITLE
How to do simple math operations on matrices? 

### ISSUE THREAD

**Issue by tastyminerals** [stepelu/lua-sci#4]
Ok, this is trivial and yet it is somehow missed from the docs it seems.

```
local alg = require "sci.alg"
A = alg.tomat({2,3,0},{1,1,-1})
B = A - 1
```

And I am getting `attempt to perform arithmetic on 'struct 1526' and 'number'`.

**Comment by stepelu** [comment]
This kind of syntax is not supported for performance reasons.

However, if you were to install the sci syntax extensions, you could invoke the `scilua` script and use:

``` lua
local alg = require "sci.alg"
A = alg.tomat({2,3,0},{1,1,-1})
B = A[] - 1
```

**Comment by sonoro1234** [comment]
@stepelu 
How this should be done without sci syntax extensions?
For multiplication we should use alg.mul but which should be used for sums?
Also: with and without sci syntax extensions, how to exponentiate (math.exp) all elements in a matrix?
How to get matrix transposed without sci syntax?
